### PR TITLE
Ensure that package creation task is executed before publishing

### LINKED ISSUE #58: {"message":"Package 'dadagen' was not found"}
When Uploading for the first time to bintray, I am getting an error stating that the package was not found.

From the documentation I can see that bintray-sbt is meant to create a new package for me// but alas I get this error
```
[error] (*:publish) error uploading to https://api.bintray.com/maven/inosion/maven/maven/org/inosion/dadagen/dadagen_2.11/0.2.6/dadagen_2.11-0.2.6-tests-javadoc.jar: {"message":"Package 'dadagen' was not found"}
```
Currently the project https://github.com/inosion/dadagen has only one artifact, but I will soon be moving it to a multi project.

I am attempting to push the library up into the Inosion Organisation on Bintray.

### PR DESCRIPTION
**Pull request by 2m**
Resolves #58.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/softprops/bintray-sbt/pull/70" target="_blank">ReviewNinja

**Comment by softprops** [comment]
thanks. I feel like this will fix a handful of issue's that popped up after the last big refactor

**Comment by dwijnand** [comment]
Would be nice if this were cut into a release..

**Comment by dhoepelman** [comment]
Indeed, 0.3.0 is basically unusable now if you have the problem this fixes.

**Comment by intracer** [comment]
+1

**Pull request merged**
