### PR TITLE
Try to get Sonatype credentials from system properties and environment variables

### PR DESCRIPTION
**Pull request by zsxwing**
In RxScala, we use Travis CI to publish artifact files to Bintray. However, it cannot synchronize to maven central automatically because the Sonatype credentials need to be typed manually.

This PR enables the user can set the Sonatype credentials in system properties or environment variables. Then we can use secure environment variables of Travis CI to set the credentials and make the synchronization automatically.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/softprops/bintray-sbt/pull/48" target="_blank">ReviewNinja

**Comment by softprops** [comment]
on, nice! thanks @zsxwing

**Comment by zsxwing** [comment]
Any plan to release a new version recently?

**Comment by softprops** [comment]
I can shoot for this weekend.

**Comment by zsxwing** [comment]
Cool. :+1:

**Comment by softprops** [comment]
[done](http://notes.implicit.ly/post/114370226509/bintray-sbt-0-2-1)

**Comment by zsxwing** [comment]
Thanks a lot!

**Pull request merged**
